import {
  Wallet,
  CreditCard,
  PiggyBank,
  Landmark,
  Coins,
  Banknote,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Store,
  Utensils,
  Coffee,
  Pizza,
  Apple,
  Beer,
  Wine,
  Cake,
  IceCream,
  Beef,
  Salad,
  Car,
  Bus,
  Plane,
  Train,
  Bike,
  Ship,
  Fuel,
  ParkingCircle,
  Truck,
  Home,
  Bed,
  Sofa,
  Lightbulb,
  Wifi,
  Phone,
  Smartphone,
  Laptop,
  Monitor,
  Tv,
  Printer,
  HardDrive,
  Server,
  Gamepad2,
  Music,
  Film,
  Headphones,
  Mic,
  Speaker,
  Radio,
  BookOpen,
  Book,
  GraduationCap,
  Briefcase,
  Building2,
  Building,
  Factory,
  Warehouse,
  Dumbbell,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Cross,
  Baby,
  Dog,
  Cat,
  Bird,
  Gift,
  PartyPopper,
  Shirt,
  Scissors,
  Sparkles,
  Flower2,
  TreePine,
  Leaf,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Snowflake,
  Umbrella,
  DollarSign,
  Euro,
  PoundSterling,
  JapaneseYen,
  IndianRupee,
  TrendingUp,
  TrendingDown,
  BarChart3,
  LineChart,
  PieChart,
  PercentCircle,
  HandCoins,
  Calculator,
  Zap,
  Droplets,
  Flame,
  Trash2,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  Camera,
  Image,
  Video,
  Ticket,
  MapPin,
  Map,
  Globe,
  Compass,
  Anchor,
  Rocket,
  Bitcoin,
  Target,
  Trophy,
  Award,
  Medal,
  Star,
  Crown,
  Gem,
  Key,
  Lock,
  Shield,
  Tag,
  Bookmark,
  Calendar,
  Clock,
  Hourglass,
  Bell,
  Mail,
  Send,
  Package,
  Box,
  Bath,
  ShowerHead,
  Toilet,
  WashingMachine,
  Activity,
  Users,
  User,
  UserRound,
  Cigarette,
  Footprints,
  FileText,
  ScrollText,
  Stamp,
  type LucideIcon,
} from "lucide-react";

export const ICON_LIBRARY: Record<string, LucideIcon> = {
  // Money / banking
  wallet: Wallet,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  coins: Coins,
  banknote: Banknote,
  receipt: Receipt,
  dollar: DollarSign,
  euro: Euro,
  pound: PoundSterling,
  yen: JapaneseYen,
  rupee: IndianRupee,
  bitcoin: Bitcoin,
  "hand-coins": HandCoins,
  calculator: Calculator,
  percent: PercentCircle,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,

  // Shopping
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  store: Store,
  tag: Tag,
  package: Package,
  box: Box,
  gift: Gift,

  // Food & drink
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  apple: Apple,
  beer: Beer,
  wine: Wine,
  cake: Cake,
  "ice-cream": IceCream,
  beef: Beef,
  salad: Salad,

  // Transport
  car: Car,
  bus: Bus,
  plane: Plane,
  train: Train,
  bike: Bike,
  ship: Ship,
  truck: Truck,
  fuel: Fuel,
  parking: ParkingCircle,

  // Home & utilities
  home: Home,
  bed: Bed,
  sofa: Sofa,
  bath: Bath,
  shower: ShowerHead,
  toilet: Toilet,
  "washing-machine": WashingMachine,
  lightbulb: Lightbulb,
  wifi: Wifi,
  flame: Flame,
  droplets: Droplets,
  zap: Zap,
  trash: Trash2,

  // Tech
  phone: Phone,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  tv: Tv,
  printer: Printer,
  "hard-drive": HardDrive,
  server: Server,

  // Entertainment
  gamepad: Gamepad2,
  music: Music,
  film: Film,
  headphones: Headphones,
  mic: Mic,
  speaker: Speaker,
  radio: Radio,
  camera: Camera,
  image: Image,
  video: Video,
  ticket: Ticket,

  // Education / work
  book: Book,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  building: Building2,
  "building-alt": Building,
  factory: Factory,
  warehouse: Warehouse,
  "file-text": FileText,
  scroll: ScrollText,
  stamp: Stamp,

  // Health / fitness
  dumbbell: Dumbbell,
  activity: Activity,
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  cross: Cross,

  // People / family
  baby: Baby,
  users: Users,
  user: User,
  "user-round": UserRound,
  footprints: Footprints,
  cigarette: Cigarette,

  // Pets / nature
  dog: Dog,
  cat: Cat,
  bird: Bird,
  flower: Flower2,
  tree: TreePine,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  snowflake: Snowflake,
  umbrella: Umbrella,

  // Misc / goals / extras
  party: PartyPopper,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  rocket: Rocket,
  target: Target,
  trophy: Trophy,
  award: Award,
  medal: Medal,
  star: Star,
  crown: Crown,
  gem: Gem,
  key: Key,
  lock: Lock,
  shield: Shield,
  bookmark: Bookmark,
  calendar: Calendar,
  clock: Clock,
  hourglass: Hourglass,
  bell: Bell,
  mail: Mail,
  send: Send,
  map: Map,
  "map-pin": MapPin,
  globe: Globe,
  compass: Compass,
  anchor: Anchor,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  palette: Palette,
};

export const ICON_NAMES = Object.keys(ICON_LIBRARY);

export const DEFAULT_ACCOUNT_ICON = "wallet";
export const DEFAULT_CATEGORY_ICON = "receipt";
export const DEFAULT_COLOR = "#00a63e";

export function getIcon(name: string | null | undefined): LucideIcon {
  if (name && ICON_LIBRARY[name]) return ICON_LIBRARY[name];
  return ICON_LIBRARY[DEFAULT_ACCOUNT_ICON];
}

export const COLOR_PALETTE: { name: string; value: string }[] = [
  // Reds
  { name: "Red 300", value: "#fca5a5" },
  { name: "Red 500", value: "#ef4444" },
  { name: "Red 600", value: "#dc2626" },
  { name: "Red 700", value: "#b91c1c" },
  { name: "Rose 400", value: "#fb7185" },
  { name: "Rose 600", value: "#e11d48" },
  { name: "Pink 400", value: "#f472b6" },
  { name: "Pink 600", value: "#db2777" },
  { name: "Pink 800", value: "#9d174d" },
  { name: "Fuchsia 500", value: "#d946ef" },
  { name: "Fuchsia 600", value: "#c026d3" },

  // Purples
  { name: "Purple 400", value: "#c084fc" },
  { name: "Purple 600", value: "#9333ea" },
  { name: "Purple 800", value: "#6b21a8" },
  { name: "Violet 500", value: "#8b5cf6" },
  { name: "Violet 600", value: "#7c3aed" },
  { name: "Indigo 500", value: "#6366f1" },
  { name: "Indigo 600", value: "#4f46e5" },
  { name: "Indigo 800", value: "#3730a3" },

  // Blues
  { name: "Blue 400", value: "#60a5fa" },
  { name: "Blue 500", value: "#3b82f6" },
  { name: "Blue 600", value: "#2563eb" },
  { name: "Blue 800", value: "#1e40af" },
  { name: "Sky 400", value: "#38bdf8" },
  { name: "Sky 600", value: "#0284c7" },
  { name: "Sky 800", value: "#075985" },

  // Cyans / teals
  { name: "Cyan 400", value: "#22d3ee" },
  { name: "Cyan 600", value: "#0891b2" },
  { name: "Cyan 800", value: "#155e75" },
  { name: "Teal 400", value: "#2dd4bf" },
  { name: "Teal 600", value: "#0d9488" },
  { name: "Teal 800", value: "#115e59" },

  // Greens
  { name: "Emerald 400", value: "#34d399" },
  { name: "Emerald 600", value: "#059669" },
  { name: "Emerald 800", value: "#065f46" },
  { name: "Green 400", value: "#4ade80" },
  { name: "Green 500", value: "#22c55e" },
  { name: "Green 600", value: "#00a63e" },
  { name: "Green 800", value: "#166534" },
  { name: "Lime 500", value: "#84cc16" },
  { name: "Lime 700", value: "#4d7c0f" },

  // Yellows / oranges
  { name: "Yellow 300", value: "#fde047" },
  { name: "Yellow 500", value: "#eab308" },
  { name: "Yellow 700", value: "#a16207" },
  { name: "Amber 400", value: "#fbbf24" },
  { name: "Amber 600", value: "#d97706" },
  { name: "Orange 400", value: "#fb923c" },
  { name: "Orange 600", value: "#ea580c" },
  { name: "Orange 800", value: "#9a3412" },

  // Browns / warm neutrals
  { name: "Stone 500", value: "#78716c" },
  { name: "Stone 700", value: "#44403c" },
  { name: "Zinc 500", value: "#71717a" },

  // Greys / neutrals
  { name: "Slate 300", value: "#cbd5e1" },
  { name: "Slate 500", value: "#64748b" },
  { name: "Slate 700", value: "#334155" },
  { name: "Gray 400", value: "#9ca3af" },
  { name: "Gray 600", value: "#4b5563" },
  { name: "Gray 800", value: "#1f2937" },

  // Whites / blacks
  { name: "White", value: "#f8fafc" },
  { name: "Black", value: "#0a0a0a" },
];
